//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Award
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_award { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual User User { get; set; }
    }
}
